---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blue
  name: blue
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - image: jpetazzo/color
        name: color
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: blue
  name: blue
  namespace: default
spec:
  ports:
  - name: "80"
    port: 80
  selector:
    app: blue